#ifndef _SIMULATED_MODULE_IDL_
#define _SIMULATED_MODULE_IDL_

/*******************************************************************************
Copyright (C) 2020 INAF

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

Authors:
Andrea Bulgarelli <andrea.bulgarelli@inaf.it>
Leonardo Baroncelli <leonardo.baroncelli@inaf.it>
Nicolo' Parmiggiani <nicolo.parmiggiani@inaf.it>
Antonio Addis <antonio.addis@inaf.it>
*******************************************************************************/

#include <acscomponent.idl>
#include <Types.idl>

#pragma prefix "sag"
 
module SIMULATED_MODULE
{
    interface SimDatabase : ACS::ACSComponent {

        /** 
        * 
        *
        * @param 
        * @raise 
        * @return 
        */        
        long getSubArrayIDFromSB(in long sbID);

    };   

    interface SimCentralControl : ACS::ACSComponent {

        /** 
        * Ask the CC for the parameters to connect with ADH and receive data for a specific SB.
        *
        * @param sbID
        * @raise 
        * @return String
        */        
        string getConnectionParametersToADH(in long sbID);

    };   
};
 
#endif