/*******************************************************************************
Copyright (C) 2020 INAF

This software is distributed under the terms of the BSD-3-Clause license

Authors:
Andrea Bulgarelli <andrea.bulgarelli@inaf.it>
Leonardo Baroncelli <leonardo.baroncelli@inaf.it>
Nicolo' Parmiggiani <nicolo.parmiggiani@inaf.it>
Antonio Addis <antonio.addis@inaf.it>
*******************************************************************************/

#ifndef _TYPES_IDL_
#define _TYPES_IDL_

#pragma prefix "sag"

module TYPES
{ 


	// NOTIFICATION CHANNELS ----------------------------------------------- 

	const string CHANNELNAME_MON = "mon";

	struct ChannelEvent_FROM_MON {
		string msg;
		long value;
	};
	struct ChannelEvent_TO_MON {
		string msg;
		long value;
	};


	const string CHANNELNAME_ADH = "adh";

	struct ChannelEvent_FROM_ADH {
		string msg;
		long value;
	};
	struct ChannelEvent_TO_ADH {
		string msg;
		long value;
	};


	const string CHANNELNAME_CC = "cc";

	struct ChannelEvent_FROM_CC {
		string msg;
		long value;
	};
	struct ChannelEvent_TO_CC {
		string msg;
		long value;
	};


	const string CHANNELNAME_RM = "rm";

	struct ChannelEvent_FROM_RM {
		string msg;
		long value;
	};
	struct ChannelEvent_TO_RM {
		string msg;
		long value;
	};


	const string CHANNELNAME_HMI = "hmi";

	struct ChannelEvent_FROM_HMI {
		string msg;
		long value;
	};
	struct ChannelEvent_TO_HMI {
		string msg;
		long value;
	};

	// INTERNAL MONITORING -------------------------------------------------
	
	struct MonitoredParam {
		string name;
		double value;
	};

	typedef sequence<MonitoredParam> MonitoredParamsList;



	// SAG TYPES ----------------------------------------------------------- 

	struct Telescope {
		string type; /* SST, MST, LST */
	};

	typedef sequence<Telescope> TelescopeList;

	struct SubArray {
		long subArrayId;
		TelescopeList sbTelescopeList;
	};

	struct Coordinates {
		double az;
		double el;
	};

	struct Target {
		long     tid;
		Coordinates tCoordinates;
		long   expTime;  /* seconds */
	};

	
	struct ObservationBlock {
		double plannedDuration;
		double scheduledStartTime;
		double actualStartTime;
		string id;
		Target obTarget;
		double executeDuration;
	};

	typedef sequence<ObservationBlock> ObservationBlockList;

	struct SchedulingBlock {
		string sBid;
		string proposalId;
		SubArray sbSubArray;
		ObservationBlockList sbObservationBlockList;
	};


};



#endif

