/*******************************************************************************
Copyright (C) 2020 INAF

This software is distributed under the terms of the BSD-3-Clause license

Authors:
Andrea Bulgarelli <andrea.bulgarelli@inaf.it>
Leonardo Baroncelli <leonardo.baroncelli@inaf.it>
Nicolo' Parmiggiani <nicolo.parmiggiani@inaf.it>
Antonio Addis <antonio.addis@inaf.it>
*******************************************************************************/

#ifndef _CONSOLE_IDL_
#define _CONSOLE_IDL_

#include <acscomponent.idl>
#include <Types.idl>
#include <CONSOLEErr.idl>



#pragma prefix "sag"


module CONSOLE_MODULE 
{
	

	interface Console :  ACS::ACSComponent
	{		
		/**
		* Activates the SAG Supervisor component.
		* @raise SAGSupervisorAlreadyActivatedEx
		* @return void
		*/
		void startSAGSupervisor()
			raises (
				CONSOLEErr::SAGSupervisorAlreadyActivatedEx
			);

		/**
		* Deactivates the SAG Supervisor component.
		* @raise SAGSupervisorAlreadyDeactivatedEx
		* @return void
		*/
		void stopSAGSupervisor()
			raises (
				CONSOLEErr::SAGSupervisorAlreadyDeactivatedEx
			);
			
			
		/**
		* Forwards the request to the SAGSupervisor
		* @raise SAGSupervisorAlreadyActivatedEx
		* @return void
		*/
		void newSchedulingBlock (in long sbID)
			raises(
				CONSOLEErr::SAGSupervisorIsNotRunningEx
			);	


		/**
		* Forwards the request to the SAGSupervisor
		* @raise SAGSupervisorAlreadyActivatedEx
		* @return void
		*/
		void stopSchedulingBlock (in long sbID)
			raises(
				CONSOLEErr::SAGSupervisorIsNotRunningEx
			);	
	
	
		/**
		* Forwards the request to the SAGSupervisor
		* @raise SAGSupervisorIsNotRunningEx
		* @return void
		*/
		void startObservation(in long sbID)
			raises (
				CONSOLEErr::SAGSupervisorIsNotRunningEx
			);
		
		/**
		* Forwards the request to the SAGSupervisor
		* @raise SAGSupervisorIsNotRunningEx
		* @return void
		*/    
		void stopObservation(in long sbID)
			raises (
				CONSOLEErr::SAGSupervisorIsNotRunningEx
			);


		/**
		* Forwards the request to the SAGSupervisor
		* @raise SAGSupervisorIsNotRunningEx
		* @return void
		*/
		void updateSubArray(in long sbID)
			raises (
				CONSOLEErr::SAGSupervisorIsNotRunningEx
			);

	};
};

#endif
